### ISSUE TITLE
Output file should not replace source file

### ISSUE THREAD

**Issue by ankurk91** [teejee2008/selene#1]
Hi, 
First of all thanks for this awesome piece of software.

First time when i tried to this software i pick a couple of video files and hit start, and you know what i lost my source files. (I was converting mp4 to mp4)
This is bad, later i come to know that i can set output folder in settings.

Can you make 'home' as default output folder. 
OR
Don't overwrite source files at all; just rename them. For example if source file was 'Example 720p.mp4' then output file name should be 'Example 720p - Converted-2016-02-20.mp4'
Ultimately user should not loose their source file in any case.

I think i am not alone, many of other users may have been facing same issue.

Thanks

**Comment by teejee2008** [comment]
Fixed in v16.2.4
