### ISSUE TITLE
Segfault if using gtk 3.20

### ISSUE THREAD

**Issue by rolandixor** [teejee2008/selene#2]
This occurs on Ubuntu if using the Gnome 3-Staging PPA.

I believe this is due to lack of Gtk 3.20 support. Not a major issue, as one can just purge the PPA, but just thought it would be nice to let you know of this issue.

**Comment by teejee2008** [comment]
Thanks. I'll look into it.

**Comment by rolandixor** [comment]
Hi, this is still occurring. I'd prefer not to downgrade from Gnome 3.20 if no other issues pop up.

Would recompiling from source fix this issue?

**Comment by Pival81** [comment]
so, nothing?

**Comment by rolandixor** [comment]
I recompiled it from source and it worked.

**Comment by Pival81** [comment]
I just tried to recompile it and it doesn't work, i'm on arch 
EDIT: just to make it clear, to compile it i just have to do make and sudo make install, right?

**Comment by hualet** [comment]
Confirm here on deepin (a distro based on debian sid). Downloaded the 64bit deb for debian from selene official site, and it crashes on startup.

**Comment by teejee2008** [comment]
Fixed in v17.4
