### ISSUE TITLE
Error importing audio-0.m4a: Requested URL is not valid or cannot be found

### ISSUE THREAD

**Issue by roo79x** [teejee2008/selene#3]
hi I have been having this problem with Selene since xubuntu 14.04. doesn't seem to matter if I try to convert an avi, mkv or any file type to mp4 all encoders are installed every time I get the same error also all dependencies xubuntu will let me install only ones it won't install are libgtk-3 libgee2 libjson-glib. 
[log.txt](https://github.com/teejee2008/selene-media-converter/files/299639/log.txt)
[log.txt](https://github.com/teejee2008/selene-media-converter/files/299641/log.txt)

is there something I as a novice are doing wrong? or is there an issue I am not knowing?
selene is an essential app for me as before this error started it encoded any file so it would play on any device I tried it on.
xubuntu 16.04 64bit current, but has not worked for me since xubuntu 14.04 64 bit. also tried on ubuntu mate 64 bit, ubuntu 64 bit, ubuntu and ubuntu gnome 64bit all versions since 14.04 all give same error everytime. also nero aac is install as per your instructions.
lastly I would like to take this time to say thankyou very much for the best video audio converter I have ever used and hope I don't have to abandon it.
If you need any information from me I will do my novice best to comply for you
again thanks
Ray Whatman

**Comment by teejee2008** [comment]
According to the attached log the Nero AAC encoder is missing on your system. You can install it with the following commands:

cd /tmp
wget http://ftp6.nero.com/tools/NeroAACCodec-1.5.1.zip
unzip -j NeroAACCodec-1.5.1.zip linux/neroAacEnc
sudo install -m 0755 neroAacEnc /usr/bin
sudo apt-get install gpac

**Comment by roo79x** [comment]
needed libc6-i386 lib32gcc1 lib32stdc++6 to get nero working on ubuntu 16.04 16.10 64 bit

found the information here http://www.linuxquestions.org/questions/linux-software-2/%5Bdebian-squeeze%5D-installing-neroaacenc-924429/#post4578605
