### ISSUE TITLE
Enquiry

### ISSUE THREAD

**Issue by aberba** [teejee2008/selene#4]
I want to know if you use GStreamer for encode/decode or ffmpeg. How do you use if - or API, I'm going through your code and I want to understand some things :)

**Comment by teejee2008** [comment]
It doesn't use gstreamer. It uses command line utilities like ffmpeg, x264, etc

**Comment by aberba** [comment]
On 07/01/2016 05:44 AM, teejee2008 wrote:

> It doesn't use gstreamer. It uses command line utilities like ffmpeg, 
> x264, etc
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> https://github.com/teejee2008/selene-media-converter/issues/4#issuecomment-229858798, 
> or mute the thread 
> https://github.com/notifications/unsubscribe/AH7fGMvp3dEVyzmuJ7-XtpGBD8frYTLtks5qRKkwgaJpZM4JCcuG.
> 
> I was planing on using GStreamer, but with how you app performs smooth 
> on my PC, i was wondering if that is why you did not go for GStreamer.

What is you opinion on GStreamer for an app like yours?
