### ISSUE TITLE
allow OPUS in WEBM

### ISSUE THREAD

**Issue by zraffer** [teejee2008/selene#8]
I'm trying to create a youtube-like output with VP9+OPUS in WEBM.

currently (selene v17.4.2 build from teejee2008 ppa) it is impossible to create a profile via GUI with WEBM and OPUS, as far as GUI does not show OPUS as audio codec after selecting WEBM as container format.

**Comment by teejee2008** [comment]
Support for OPUS in WebM, MKV and OGG added in v17.7
